<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="BPELProcess" targetNamespace="http://xmlns.oracle.com/Auditory/AuditoryBroker/BPELProcess" xmlns:ns1="http://xmlns.oracle.com/AuditoryBroker" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:client="http://xmlns.oracle.com/Auditory/AuditoryBroker/BPELProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <wsdl:documentation/>
   <plnk:partnerLinkType name="BPELProcess">
      <plnk:role name="BPELProcessProvider" portType="client:BPELProcess"/>
   </plnk:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/AuditoryBroker" schemaLocation="http://172.30.13.35:8001/soa-infra/services/PruebasSOA/AuditoryBroker/bpelprocess_client_ep?XSD=xsd/AuditoryBroker.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="BPELProcessRequestMessage">
      <wsdl:part name="payload" element="ns1:AuditoryBrokerRequest"/>
   </wsdl:message>
   <wsdl:portType name="BPELProcess">
      <wsdl:operation name="process">
         <wsdl:input message="client:BPELProcessRequestMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <wsdl:binding name="BPELProcessBinding" type="client:BPELProcess">
      <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="process">
         <soap:operation style="document" soapAction="process"/>
         <wsdl:input>
            <soap:body use="literal"/>
         </wsdl:input>
      </wsdl:operation>
   </wsdl:binding>
   <wsdl:service name="bpelprocess_client_ep">
      <wsdl:port name="BPELProcess_pt" binding="client:BPELProcessBinding">
         <soap:address location="http://172.30.13.35:8001/soa-infra/services/PruebasSOA/AuditoryBroker/bpelprocess_client_ep"/>
      </wsdl:port>
   </wsdl:service>
</wsdl:definitions>
